version: '3.7'

services:
  phone:
    container_name: phone
    image: node:erbium
    build: ./
    restart: unless-stopped
    depends_on:
      - mongodb
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=twilio-phone-ng_webphone-network"
      - "traefik.http.routers.phone.rule=Host(`phone.${DOMAIN}`)"
      - "traefik.http.routers.phone.entrypoints=http"
      - "traefik.http.routers.phone.middlewares=redirect@file"
      - "traefik.http.routers.phone-secured.rule=Host(`phone.${DOMAIN}`)"
      - "traefik.http.routers.phone-secured.entrypoints=https"
      - "traefik.http.routers.phone-secured.middlewares=hsts@file"
      - "traefik.http.routers.phone-secured.tls=true"
    environment:
      - "MONGODB_URI=mongodb://mongodb:27017/phone"
      - "SESSION_SECRET=${SESSION_SECRET}"
    # ports:
    #  - "5000:5000"
    networks:
      webphone-network:
        aliases:
          - phone

  mongodb:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    volumes:
      - mongodb:/data/db
    # ports:
    #  - "27017:27017"
    networks:
      webphone-network:
        aliases:
          - mongodb

networks:
  webphone-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: webphone-br
    ipam:
      driver: default
      config:
        - subnet: ${IPV4_NETWORK:-172.16.1}.0/24

volumes:
  mongodb:
